<%
director_uuid = "CHANGE-ME"
deployment_name = "zipkin"
elastic_ip = "CHANGE-ME"
num_collectors = 3
num_queries = 3
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: zipkin
   version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    security_groups:
      tags:
        - bosh
        - <%= deployment_name %>

  - name: elastic
    type: vip
    cloud_properties: {}

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.medium

jobs:
  - name: redis
    templates:
      - name: redis
    instances: 1
    resource_pool: default
    persistent_disk: 10240
    networks:
      - name: default
        default: [dns, gateway]

  - name: zipkin_collector
    templates:
      - name: zipkin_collector
    instances: <%= num_collectors %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: zipkin_query
    templates:
      - name: zipkin_query
    instances: <%= num_queries %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: zipkin_web
    templates:
      - name: zipkin_web
    instances: 1
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]
      - name: static
        static_ips:
          - <%= elastic_ip %>

properties:
  redis:
    address: 0.redis.default.<%= deployment_name %>.microbosh

  zipkin:
    store: "redis"
    query:
      servers:
        <% num_queries.times do |i| %>
        <%= "- #{i}.zipkin-query.default.#{deployment_name}.microbosh\n" %>
        <% end %>
